#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
done
